import "./globals.css";
import { FAMILY } from "@/utils/constants";
import { AppProvider } from "./provider";
import Navbar from "@/components/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`ubuntu w-screen overflow-x-hidden h-screen text-[var(--primary-text)] bg-[var(--bg)]`}>
        <AppProvider>
          <Navbar/>
          {children}

        </AppProvider>
      </body>
    </html>
  );
}
